---
name: Text-Sass
version: 0.2
author:
  - 'Roger Pettett <rmp@psyphi.net>'
abstract: 'Text-Sass - Perl implementation of http://sass-lang.com/'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Distribution: 2.00
  Test::More: 0.8
  Test::Perl::Critic: 1.01
requires:
  Carp: 1.04
  strict: 1.03
  warnings: 1.05
configure_requires:
  Module::Build: 0.35
provides:
  Text::Sass:
    file: lib/Text/Sass.pm
    version: 0.2
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
