---
abstract: 'Text-Sass - Perl implementation of http://sass-lang.com/'
author:
  - 'Roger Pettett <rmp@psyphi.net>'
build_requires:
  Test::More: 0.8
  Try::Tiny: 0.06
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Sass
provides:
  Text::Sass:
    file: lib/Text/Sass.pm
    version: v0.8.1
  Text::Sass::ColorFunctions:
    file: lib/Text/Sass/ColorFunctions.pm
    version: 0.1
  Text::Sass::Expr:
    file: lib/Text/Sass/Expr.pm
    version: 0.1
recommends:
  Data::Dumper: 2.125
requires:
  Carp: 1.04
  English: 1.02
  Readonly: 1.03
  strict: 1.03
  warnings: 1.05
resources:
  license: http://dev.perl.org/licenses/
version: v0.8.1
