---
abstract: 'Text-Sass - Perl implementation of http://sass-lang.com/'
author:
  - 'Roger Pettett <rmp@psyphi.net>'
build_requires:
  Test::More: 0.8
  Try::Tiny: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Sass
provides:
  Text::Sass:
    file: lib/Text/Sass.pm
    version: 0.93
  Text::Sass::Expr:
    file: lib/Text/Sass/Expr.pm
    version: 0.1
  Text::Sass::Functions:
    file: lib/Text/Sass/Functions.pm
    version: 0.1
recommends:
  Data::Dumper: 2.125
requires:
  Carp: 1.04
  Convert::Color: 0.05
  English: 1.02
  POSIX: 1.09
  Readonly: 1.03
  strict: 1.03
  warnings: 1.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.93
